---
- name: Instalação do Docker
  hosts: all
  tasks:
  
  - name: Instalar os pré-requisitos
    apt:
      name: ca-certificates, curl, gnupg, lsb-release
      state: present
    become: true

  - name: Adicionando chave para o repositório apt
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    become: true

  - name: Adicionando o repositório para instalar o Docker
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
      state: present
    become: true

  - name: Instalação do Docker
    apt:
      update_cache: yes
      name: docker-ce
      state: present
    become: true

- name: Instalar as dependecias para executar o modulo Docker
  hosts: all
  tasks:
    - name: Instalação do PIP
      apt:
        name: python3-pip
        state: latest
        update_cache: yes
      become: true 

    - name: Instalação do pacote docker do Python
      pip:
        name: docker 
      become: true

- name: Executar o container da aplicação
  hosts: all
  tasks:

  - name: Executar a criação do container 
    community.docker.docker_container:
      name: conversao 
      image: fabricioveronez/conversao-temperatura:v1
      published_ports: "8080:8080"
    become: true
