---
- name: Install the prerequisites
  apt:
    name: ca-certificates, curl, gnupg, lsb-release
    state: present
  become: true

- name: Adding key to apt repository
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: true

- name: Adding the repository to install Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
    state: present
  become: true

- name: Installing docker
  apt:
    update_cache: yes
    name: docker-ce
    state: present
  become: true

- name: Installing pip
  apt:
    update_cache: yes
    name: python3-pip
    state: latest
  become: true 

- name: Installing the Python docker package
  pip:
    name: docker 
  become: true
# tasks file for docker_install
